plugins {
    id 'com.android.application'
}

android {
    namespace 'io.github.kemou2333.campusinbox'
    compileSdk 36

    defaultConfig {
        applicationId 'io.github.kemou2333.campusinbox'
        minSdk 26
        targetSdk 36
        versionCode 4
        versionName '2.2.0'
    }

    signingConfigs {
        release {
            def signingPath = System.getenv('ANDROID_KEYSTORE_PATH')
            if (signingPath) {
                storeFile file(signingPath)
                storePassword System.getenv('ANDROID_KEYSTORE_PASSWORD')
                keyAlias System.getenv('ANDROID_KEY_ALIAS')
                keyPassword System.getenv('ANDROID_KEY_PASSWORD')
            }
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        buildConfig true
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.16.0'
}
