server {
    listen 80;
    server_name 123.57.30.129;
    access_log off;
    location ^~ /.well-known/acme-challenge/ {
        root /var/www/campus-acme;
        default_type text/plain;
        try_files $uri =404;
    }
    location / { return 404; }
}
